version: '3'
services:
    flask:
        hostname: flask
        image: "oakland/flask"
        ports:
            - "5000:5000"
        links:
            - mongo:mongo
            - redis:redis
    sockets:
        hostname: sockets
        image: "oakland/sockets"
        ports:
            - "5001:5001"
        links:
            - mongo:mongo
            - redis:redis
    vue:
        hostname: vue
        image: "oakland/vue"
        ports:
            - "80:80"
    mongo:
        image: "mongo:latest"
<<<<<<< HEAD
        ports:
            - "27017:27017"
=======
    redis:
        image: "redis:alpine"
>>>>>>> refs/remotes/origin/development

