version: '3'
services:
    flask:
        hostname: flask
        image: "oakland/flask"
        ports:
            - "8443:8443"
        links:
            - mongo:mongo
            - redis:redis
    sockets:
        hostname: sockets
        image: "oakland/sockets"
        ports:
            - "80:80"
        links:
            - mongo:mongo
            - redis:redis
    vue:
        hostname: vue
        image: "oakland/vue"
        ports:
            - "8081:8081"
    mongo:
        image: "mongo:latest"
    redis:
        image: "redis:alpine"
